### ISSUE TITLE
Failed to activate the collab package

### ISSUE THREAD

**Issue by marty80** [lolkittens/Collab#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [collab](https://github.com/lolkittens/Collab) package, v0.1.0

### Stack Trace

Failed to activate the collab package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (C:\Users\220983F\.atom\packages\collab\lib\collab.coffee:10:23)
  at Package.module.exports.Package.activateNow (C:\Users\220983F\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
  at C:\Users\220983F\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:772:25
  at Emitter.module.exports.Emitter.emit (C:\Users\220983F\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\220983F\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (C:\Users\220983F\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\220983F\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\220983F\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:11.2.0 collab:server (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-monokai"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-monokai, v0.8.0
collab, v0.1.0
git-diff-details, v0.18.0
git-go, v1.0.1
git-log, v0.4.1
git-projects, v1.14.1
git-tab-status, v1.9.2
language-cfml, v0.7.1
minimap, v4.10.0
minimap-git-diff, v4.1.3
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by lolkittens** [comment]
Sorry but I no longer maintain this package since I moved to Android development shortly after starting this project.

It's unlikely I will revisit this project anytime soon, there are better alternatives available for atom like https://atom.io/packages/motepair

**Comment by marty80** [comment]
No problem. Thanks for suggesting motepair. All the best.
